GENGKAPAK_BUILD_TYPE ?= OFFICIAL
GENGKAPAK_VERSION ?= SLAV

CUSTOM_DATE_YEAR := $(shell date -u +%Y)
CUSTOM_DATE_MONTH := $(shell date -u +%m)
CUSTOM_DATE_DAY := $(shell date -u +%d)
CUSTOM_DATE_HOUR := $(shell date -u +%H)
CUSTOM_DATE_MINUTE := $(shell date -u +%M)
GENGKAPAK_BUILD_DATE_UTC := $(shell date -d '$(CUSTOM_DATE_YEAR)-$(CUSTOM_DATE_MONTH)-$(CUSTOM_DATE_DAY) $(CUSTOM_DATE_HOUR):$(CUSTOM_DATE_MINUTE) UTC' +%s)
GENGKAPAK_BUILD_DATE := $(CUSTOM_DATE_YEAR)$(CUSTOM_DATE_MONTH)$(CUSTOM_DATE_DAY)-$(CUSTOM_DATE_HOUR)$(CUSTOM_DATE_MINUTE)

GENGKAPAK_PLATFORM_VERSION := 12.0

TARGET_PRODUCT_SHORT := $(subst gengkapak_,,$(GENGKAPAK_BUILD))

CUSTOM_VERSION := GengKapak-$(GENGKAPAK_PLATFORM_VERSION)-$(GENGKAPAK_BUILD_TYPE)-$(GENGKAPAK_BUILD_DATE)
CUSTOM_VERSION_PROP := slav
